name: Bootstrap
logo: docs/assets/brand/bootstrap-solid.svg

excludeDir:
  - dist
  - docs

assets:
  - dist
  - fonts

sidebar:
  background: "#3b2a55"
  textColor: "#fff"

headHtml: |
  <link rel="stylesheet" href="dist/css/bootstrap.min.css">

bodyHtml: |
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="dist/js/bootstrap.min.js"></script>

order:
  - +Getting Started
